rss = [("ScienceDirect Publication: Biotechnology Advances", "http://rss.sciencedirect.com/publication/science/07349750"),
       ("Wiley: Arthritis Care & Research: Table of Contents", "https://onlinelibrary.wiley.com/action/showFeed?jc=21514658&type=etoc&feed=rss"),
       ("Frontiers in Immunology", "https://www.frontiersin.org/journals/immunology/rss"),
       ("Annual Reviews: Annual Review of Immunology: Table of Contents", "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sl&jc=immunol&type=etoc&feed=rss"),
       ("ScienceDirect Publication: Clinical Immunology", "http://rss.sciencedirect.com/publication/science/15216616"),
       ("ScienceDirect Publication: Molecular Cell", "http://rss.sciencedirect.com/publication/science/10972765"),
       ("ScienceDirect Publication: Neuroscience", "http://rss.sciencedirect.com/publication/science/03064522"),
       ("ScienceDirect Publication: Journal of Autoimmunity", "https://www.journals.elsevier.com/journal-of-autoimmunity/rss"),
       ("ScienceDirect Publication: EBioMedicine", "http://rss.sciencedirect.com/publication/science/23523964"),
       ("ScienceDirect Publication: DNA Repair", "http://rss.sciencedirect.com/publication/science/15687864"),
       ("ScienceDirect Publication: Bioorganic Chemistry", "http://rss.sciencedirect.com/publication/science/00452068"),
       ("ScienceDirect Publication: Biology of Blood and Marrow Transplantation", "http://rss.sciencedirect.com/publication/science/10838791"),
       ("ScienceDirect Publication: Cancer Treatment Reviews", "http://rss.sciencedirect.com/publication/science/03057372"),
       ("ScienceDirect Publication: Neuropharmacology", "http://rss.sciencedirect.com/publication/science/00283908"),
       ("ScienceDirect Publication: European Journal of Medicinal Chemistry", "https://www.journals.elsevier.com/european-journal-of-medicinal-chemistry/rss"),
       ("Antimicrobial Agents and Chemotherapy", "https://aac.asm.org/rss/current.xml"),
       ("Journal of Antimicrobial Chemotherapy", "https://academic.oup.com/rss/site_5301/3167.xml"),
       ("PLOS Biology: New Articles", "http://biology.plosjournals.org/perlserv/?request=get-rss&issn=1545-7885&type=new-articles", "1544-9173"),
       ("ScienceDirect Publication: Cell", "http://rss.sciencedirect.com/publication/science/00928674", "0092-8674"),
       ("Molecular Therapy", "http://rss.sciencedirect.com/publication/science/15250016", "1525-0016"),
       ("Current Opinion in Immunology - Just Published", "http://www.current-opinion.com/rss/just-published/current-opinion-in-immunology/", "0952-7915"),
       ("ScienceDirect Publication: Metabolic Engineering", "http://rss.sciencedirect.com/publication/science/10967176", "1096-7176"),
       ("Wiley: The Journal of Gene Medicine: Table of Contents", "https://onlinelibrary.wiley.com/action/showFeed?jc=15212254&type=etoc&feed=rss", "1099-498X"),
       ("Wiley: Angewandte Chemie", "https://onlinelibrary.wiley.com/feed/15213773/most-recent"),
       ("Wiley: Chemical Biology & Drug Design", "https://onlinelibrary.wiley.com/feed/17470285/most-recent"),
       ("Wiley: Cancer Science", "https://onlinelibrary.wiley.com/feed/13497006/most-recent"),
       ("Wiley: Journal of Biochemical and Molecular Toxicology", "https://onlinelibrary.wiley.com/feed/10990461/most-recent"),
       ("Wiley: Journal of Cellular and Molecular Medicine", "https://onlinelibrary.wiley.com/feed/15824934/most-recent"),
       ("Wiley: International Journal of Cancer", "https://onlinelibrary.wiley.com/feed/10970215/most-recent"),
       ("Wiley: Journal of Cellular Physiology", "https://onlinelibrary.wiley.com/feed/10974652/most-recent"),
       ("Wiley: Hepatology", "https://aasldpubs.onlinelibrary.wiley.com/action/showFeed?jc=15273350&type=etoc&feed=rss"),
       ("JAIDS", "https://cdn.journals.lww.com/jaids/_layouts/15/OAKS.Journals/feed.aspx?FeedType=CurrentIssue"),
       ("Wiley: Journal of Viral Hepatology", "https://onlinelibrary.wiley.com/feed/13652893/most-recent"),
       ("ScienceDirect Publication: Immunity", "http://rss.sciencedirect.com/publication/science/10747613", "1074-7613"),
       ("Massachusetts Medical Society: New England Journal of Medicine: Table of Contents", "http://content.nejm.org/rss/current.xml"),
       ("ScienceDirect Publication: Journal of Biotechnology", "http://rss.sciencedirect.com/publication/science/01681656"),
       ("ScienceDirect Publications: Bioorganic and Medicinal Chemistry Letters", "http://rss.sciencedirect.com/publication/science/0960894X"),
       ("Cancer Cell", "http://rss.sciencedirect.com/publication/science/15356108"),
       ("ScienceDirect Publication: Tetrahedron", "https://rss.sciencedirect.com/publication/science/00404020"),
       ("Science Immunology current issue", "http://immunology.sciencemag.org/rss/current.xml"),
       ("Science Translational Medicine", "http://stm.sciencemag.org/rss/current.xml?_ga=2.174655714.1749457138.1528469008-922381873.1528469008"),
       ("Science Signaling", "http://stke.sciencemag.org/rss/current.xml"),
       ("Science current issue", "http://www.sciencemag.org/rss/current.xml"),
       ("Blood current issue", "http://www.bloodjournal.org/rss/current.xml"),
       ("JAMA Oncology Current Issue", "http://oncology.jamanetwork.com/rss/site_159/174.xml"),
       ("JAMA Current Issue", "http://jama.jamanetwork.com/rss/site_3/67.xml"),
       ("The Journal of Immunology current issue", "http://www.jimmunol.org/rss/current.xml"),
       ("Aging and Disease-Forthcoming Articles", "http://www.aginganddisease.org/EN/rss_zxly_2152-5250.xml"),
       ("Aging and Disease-Current Issue", "http://www.aginganddisease.org/EN/rss_dqml_2152-5250.xml"),
       ("Clinical Cancer Research current issue", "http://clincancerres.aacrjournals.org/rss/current.xml"),
       ("JNCI: Journal of the National Cancer Institute Current Issue", "http://jnci.oxfordjournals.org/rss/current.xml"),
       ("Proceedings of the National Academy of Sciences current issue", "http://www.pnas.org/rss/current.xml"),
       ("Most Recent Articles: Arthritis Research & Therapy", "http://arthritis-research.com/latest/rss"),
       ("Journal of Allergy and Clinical Immunology", "http://www.jacionline.org/current.rss"),
       ("Wiley: Biotechnology Journal: Table of Contents", "https://onlinelibrary.wiley.com/action/showFeed?jc=18607314&type=etoc&feed=rss"),
       ("Annals of Oncology Current Issue", "http://annonc.oxfordjournals.org/rss/current.xml"),
       ("Trends in Biotechnology", "http://www.cell.com/trends/biotechnology/current.rss"),
       ("Most Recent Articles: Clinical Epigenetics", "https://clinicalepigeneticsjournal.biomedcentral.com/articles/most-recent/rss.xml"),
       ("The Lancet Oncology comments", "http://www.thelancet.com/rssfeed/lanonc_online.xml"),
       ("The Lancet Oncology", "https://www.thelancet.com/rssfeed/lanonc_current.xml?code=lancet-site"),
       ("Glycobiology Current Issue", "http://glycob.oxfordjournals.org/rss/current.xml"),
       ("Rheumatology Advance Access", "https://academic.oup.com/rss/site_5347/advanceAccess_3213.xml"),
       ("Nucleic Acids Research Current Issue", "http://nar.oxfordjournals.org/rss/current.xml"),
       ("Latest Results for Applied Microbiology and Biotechnology", "http://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=253&channel- name=Applied%20Microbiology%20and%20Biotechnology"),
       ("Rheumatology Current Issue", "https://academic.oup.com/rss/site_5347/3213.xml"),
       ("Wiley: Immunological Reviews: Table of Contents", "https://onlinelibrary.wiley.com/action/showFeed?jc=1600065x&type=etoc&feed=rss"),
       ("Wiley: Journal of Leukocyte Biology: Table of Contents", "https://jlb.onlinelibrary.wiley.com/action/showFeed?jc=19383673&type=etoc&feed=rss"),
       ("Wiley: CA: A Cancer Journal for Clinicians: Table of Contents", "https://onlinelibrary.wiley.com/action/showFeed?jc=15424863&type=etoc&feed=rss"),
       ("Wiley: Biotechnology and Bioengenineering", "https://onlinelibrary.wiley.com/action/showFeed?jc=10970290&type=etoc&feed=rss"),
       ("Latest Results for Journal of Molecular Medicine", "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=109&channel-name=Journal+of+Molecular+Medicine"),
       ("Rheumatology Current Issue", "http://rheumatology.oxfordjournals.org/rss/current.xml"),
       ("Latest Results for GeroScience", "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=11357&channel-name=GeroScience"),
       ("Clinical Rheumatology", "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=10067&channel-name=Clinical+Rheumatology"),
       ("Nature Reviews Immunology - Issue - nature.com science feeds", "http://feeds.nature.com/nri/rss/current"),
       ("Nature Communications - current - nature.com science feeds", "http://feeds.nature.com/ncomms/rss/current"),
       ("British Journal of Cancer - Issue - nature.com science feeds", "http://feeds.nature.com/bjc/rss/current"),
       ("Blood Cancer Journal - Issue - nature.com science feeds", "http://feeds.nature.com/bcj/rss/current"),
       ("Leukemia - Issue - nature.com science feeds", "http://feeds.nature.com/leu/rss/current"),
       ("Nature - Issue - nature.com science feeds", "http://feeds.nature.com/nature/rss/current"),
       ("Oncogene - Issue - nature.com science feeds", "http://feeds.nature.com/onc/rss/current"),
       ("Nature Biotechnology", "http://www.nature.com/nbt/current_issue/rss/"),
       ("Nature Reviews Cancer - Issue - nature.com science feeds", "http://feeds.nature.com/nrc/rss/current"),
       ("Nature Immunology - Issue - nature.com science feeds", "http://feeds.nature.com/ni/rss/current"),
       ("Nature Reviews Rheumatology - Issue - nature.com science feeds", "http://feeds.nature.com/nrrheum/rss/current"),
       ("Nature Reviews Molecular Cell Biology", "http://feeds.nature.com/nrm/rss/current"),
       ("Nature Medicine - Issue - nature.com science feeds", "http://feeds.nature.com/nm/rss/current"),
       ("Cell Death and Disease - nature.com science feeds", "http://feeds.nature.com/cddis/rss/current"),
       ("Mucosal Immunology - Issue - nature.com science feeds", "http://feeds.nature.com/mi/rss/current"),
       ("Cellular & Molecular Immunology - Issue - nature.com science feeds", "http://feeds.nature.com/cmi/rss/current"),
       ("Journal of Medicinal Chemistry", "http://feeds.feedburner.com/acs/jmcmar"),
       ("Journal of Organic Chemistry", "http://feeds.feedburner.com/acs/joceah"),
       ("Organic Process Research & Development", "http://feeds.feedburner.com/acs/oprdfk"),
       ("Journal of Chemical Information and Modelling", "http://feeds.feedburner.com/acs/jcisd8"),
       ("Biochemistry", "http://feeds.feedburner.com/acs/bichaw"),
       ("Bioconjugate Chemistry", "http://feeds.feedburner.com/acs/bcches"),
       ("Chemical Reviews", "http://feeds.feedburner.com/acs/chreay"),
       ("Organic Letters", "http://feeds.feedburner.com/acs/orlef7"),
       ("Journal of the American Chemical Society", "http://feeds.feedburner.com/acs/jacsat"),
       ("Journal of Clinical Oncology", "http://ascopubs.org/action/showFeed?type=etoc&feed=rss&jc=jco")]
